//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Reviews
    {
        public int ReviewID { get; set; }
        public string Name { get; set; }
        public string UserReview { get; set; }
        public int Stars { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Review_Date { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual User User { get; set; }
    }
}
